# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Hero.create(name: "Ana", real_name: "Ana Amari", health: 200, armour: 0, shield: 0)
Hero.create(name: "Bastion", real_name: "SST Laboratories Siege Automaton E54", health: 200, armour: 100, shield: 0)
Hero.create(name: "D.Va", real_name: "Hana Song", health: 200, armour: 400, shield: 0)
Hero.create(name: "Genji", real_name: "Genji Shimada", health: 200, armour: 0, shield: 0)
Hero.create(name: "Hanzo", real_name: "Hanzo Shimada", health: 200, armour: 0, shield: 0)
Hero.create(name: "Junkrat", real_name: "Jamison Fawkes", health: 200, armour: 0, shield: 0)
Hero.create(name: "L\u00facio", real_name: "L\u00facio Correia dos Santos", health: 200, armour: 0, shield: 0)
Hero.create(name: "McCree", real_name: "Jesse McCree", health: 200, armour: 0, shield: 0)
Hero.create(name: "Mei", real_name: "Mei-Link Zhou", health: 250, armour: 0, shield: 0)
Hero.create(name: "Mercy", real_name: "Angela Ziegler", health: 200, armour: 0, shield: 0)
Hero.create(name: "Pharah", real_name: "Fareeha Amari", health: 200, armour: 0, shield: 0)
Hero.create(name: "Reaper", real_name: "Gabriel Reyes", health: 250, armour: 0, shield: 0)
Hero.create(name: "Reinhardt", real_name: "Reinhardt Wilhelm", health: 300, armour: 200, shield: 0)
Hero.create(name: "Roadhog", real_name: "Mako Rutledge", health: 600, armour: 0, shield: 0)
Hero.create(name: "Soldier: 76", real_name: "Jack Morrison", health: 200, armour: 0, shield: 0)
Hero.create(name: "Symmetra", real_name: "Satya Vaswani", health: 100, armour: 0, shield: 0)
Hero.create(name: "Torbj\u00f6rn", real_name: "Torbj\u00f6rn Lindholm", health: 200, armour: 0, shield: 0)
Hero.create(name: "Tracer", real_name: "Lena Oxton", health: 150, armour: 0, shield: 0)
Hero.create(name: "Widowmaker", real_name: "Am\u00e9lie Lacroix", health: 200, armour: 0, shield: 0)
Hero.create(name: "Winston", real_name: "Winston", health: 400, armour: 100, shield: 0)
Hero.create(name: "Zarya", real_name: "Aleksandra Zaryanova", health: 200, armour: 0, shield: 200)
Hero.create(name: "Zenyatta", real_name: "Tekhartha Zenyatta", health: 50, armour: 0, shield: 150)
Hero.create(name: "Sombra", real_name: "\u2591\u2591\u2591\u2591\u2591\u2591", health: 200, armour: 0, shield: 0)
Hero.create(name: "Orisa", real_name: "Orisa", health: 200, armour: 200, shield: 0)